---
- name: Install DevSpaces
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install DevSpaces Operator in all-namespaces mode
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: devspaces
            namespace: openshift-operators
          spec:
            channel: stable
            installPlanApproval: Automatic
            name: devspaces
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Wait for DevSpaces Operator to be ready
      ansible.builtin.pause:
        minutes: 2

    - name: Create DevSpaces namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-devspaces

    - name: Create DevSpaces CheCluster
      k8s:
        state: present
        definition:
          apiVersion: org.eclipse.che/v2
          kind: CheCluster
          metadata:
            name: devspaces
            namespace: openshift-devspaces
          spec:
            components:
              cheServer:
                debug: false
                logLevel: INFO
            devEnvironments:
              defaultEditor: che-incubator/che-code/latest
              defaultNamespace:
                autoProvision: true
                template: <username>-devspaces
            networking: {}

    - name: Wait for DevSpaces deployment to be ready
      ansible.builtin.pause:
        minutes: 5
        
    - name: Get DevSpaces route URL
      ansible.builtin.command: oc get route devspaces -n openshift-devspaces -o jsonpath='{.spec.host}'
      register: devspaces_url
      ignore_errors: yes
      
    # - name: Create admin namespace for DevSpaces
    #   k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: Namespace
    #       metadata:
    #         name: admin-devspaces
    #         labels:
    #           kubernetes.io/metadata.name: admin-devspaces
    #           app.kubernetes.io/part-of: che.eclipse.org
    #           app.kubernetes.io/component: workspaces-namespace
    #   when: devspaces_url.rc == 0
        
    
        
