---
# Playbook to apply Kubernetes manifest and patch OpenShift console
- name: Kubernetes Operations
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Apply Kubernetes manifest
      k8s:
        state: present
        src: ../resources/RHSI/site-plugin-manifest.yaml
      register: manifest_result
    
    - name: Display manifest application result
      debug:
        var: manifest_result
        verbosity: 1
    
    - name: Get current console configuration
      k8s_info:
        api_version: operator.openshift.io/v1
        kind: Console
        name: cluster
      register: console_info

    - name: Set fact for combined plugins
      set_fact:
        combined_plugins: "{{ (console_info.resources[0].spec.plugins | default([])) + ['kuadrant-console-plugin', 'openshift-site-plugin'] | unique }}"

    - name: Update console with combined plugins
      k8s:
        state: present
        api_version: operator.openshift.io/v1
        kind: Console
        name: cluster
        merge_type: merge
        definition:
          spec:
            plugins: "{{ combined_plugins }}"
    
    # - name: Display patch result
    #   debug:
    #     var: patch_result
    #     verbosity: 1