---
- name: Install Operators from OperatorHub and Enable Kubernetes Gateway API
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display installation message
      debug:
        msg: "This playbook installs operators from OperatorHub and enables the Kubernetes Gateway API"

    - name: Apply subscriptions file
      k8s:
        state: present
        src: ../resources/subscriptions.yaml

    - name: Wait for servicemesh-operator3 to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep servicemesh-operator3 | grep Running
      register: servicemesh_result
      until: servicemesh_result.rc == 0
      retries: 30
      delay: 10

    - name: Wait for kiali-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep kiali-operator | grep Running
      register: kiali_result
      until: kiali_result.rc == 0
      retries: 30
      delay: 10

    - name: Wait for opentelemetry-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep opentelemetry-operator | grep Running
      register: opentelemetry_result
      until: opentelemetry_result.rc == 0
      retries: 30
      delay: 10

    - name: Wait for tempo-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep tempo-operator | grep Running
      register: tempo_result
      until: tempo_result.rc == 0
      retries: 30
      delay: 10

    - name: Display success message
      debug:
        msg: "All operators were installed successfully"

    - name: Get list of running pods in openshift-operators namespace
      shell:
        cmd: oc get pods -n openshift-operators
      register: operator_pods

    - name: Display pods
      debug:
        var: operator_pods.stdout_lines

    - name: Check if Gateway API CRD exists
      k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: gateways.gateway.networking.k8s.io
      register: gateway_crd
      ignore_errors: true

    - name: Apply Gateway API CRDs if not present
      shell:
        cmd: oc kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0" | oc apply -f -
      when: gateway_crd.resources | length == 0

    - name: Wait for authorino-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep authorino-operator | grep Running
      register: authorino_result
      until: authorino_result.rc == 0
      retries: 30
      delay: 10


    - name: Wait for dns-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep dns-operator | grep Running
      register: dns_result
      until: dns_result.rc == 0
      retries: 30
      delay: 10


    - name: Wait for limitador-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep limitador-operator | grep Running
      register: limitador_result
      until: limitador_result.rc == 0
      retries: 30
      delay: 10


    - name: Wait for rhcl-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep kuadrant-operator | grep Running
      register: rhcl_result
      until: rhcl_result.rc == 0
      retries: 30
      delay: 10

    - name: Wait for rhsi-operator to be running
      shell:
        cmd: oc get pods -n openshift-operators | grep skupper-controller | grep Running
      register: rhsi_result
      until: rhsi_result.rc == 0
      retries: 30
      delay: 10